version: '3.7'

services:
  api:
    build:
      context: ./docker
      dockerfile: dev.Dockerfile
    command: ["yarn", "dev"]
    env_file: .env
    ports:
      - 4000:80
    volumes:
      - ./:/app
    working_dir: /app
